### ISSUE TITLE
上と下両方の壁の生成。

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/GravitySwitch#4]

**Comment by fummicc1** [comment]
__質問です。__
# やりたいこと
`Instantiate関数`で生成するObjectの場所を任意の親の子に位置に生成したい。
# なぜか
上と下の二つの壁で、下の写真のようなヒエラルキーになってるんですけど、この`UpWallController`の下に壁グループのオブジェクトを入れたいです！`unity c# instantiate 場所`で調べても出てこなかったので質問しました！
<img width="1440" alt="2018-09-20 18 03 36" src="https://user-images.githubusercontent.com/28649401/45807929-82af2980-bcff-11e8-8c95-16f4ddcc5324.png">

実際に動かすと下の写真のように一番上の階層にObjectが生成されてしまう。
<img width="1440" alt="2018-09-20 18 06 51" src="https://user-images.githubusercontent.com/28649401/45808141-0ff27e00-bd00-11e8-9254-644509d2feb2.png">

**Comment by m1ya** [comment]
'SetParent()'っていう関数があるので調べて見てください！

**Comment by fummicc1** [comment]
<img width="1440" alt="2018-09-20 18 17 46" src="https://user-images.githubusercontent.com/28649401/45808742-82b02900-bd01-11e8-9ac9-fc80bdb607d9.png">

# _DONE!!_

# 参考リンク
https://docs.unity3d.com/2017.4/Documentation/ScriptReference/Transform.SetParent.html
