### ISSUE TITLE
壁の色をランダムにする。

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/GravitySwitch#6]

**Comment by fummicc1** [comment]
## やること
-

**Comment by fummicc1** [comment]
### やること
 - 色に対応する数字に乱数を設定。(0 -> 赤, 1 -> 青みたいな)
 - materialの取得
 - materialの色をコードで変更。

**Comment by m1ya** [comment]
シマシマにする必要ある！

**Comment by fummicc1** [comment]
@m1ya ありますかね。返信遅れました。。。
